# Deploy the HPA for Application pods
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: admin-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: admin-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bsp-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bsp-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chat-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deeplink-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deeplink-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: delivery-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: delivery-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: location-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: location-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: log-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: menu-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: menu-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 55
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 55


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: promotion-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: promotion-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sync-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sync-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: upload-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upload-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-autoscaler
  namespace: ltnodeappuat
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 55
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 55


---

